### PR TITLE
Impl new fn `parse_entry_streaming` & struct `TarEntryStreaming`

### PR DESCRIPTION
**Pull request by NobodyXu**
This can be used to implement streaming mode decompression, which can use with sync reader such as `std::io::Read`, or async reader such as `tokio::io::AsyncRead`.

### CODE REVIEW

**Comment by Berrysoft** [comment]
Thank you! I have always wanted such feature.

**Comment by Berrysoft** [comment]
I've found that `content_offset` is not the real offset in the file. I've changed it to `header_len`. To get the real offset, you should add `header_len` to the offset of the header.

**Comment by NobodyXu** [comment]
> I've found that `content_offset` is not the real offset in the file. I've changed it to `header_len`. To get the real offset, you should add `header_len` to the offset of the header.

I was thinking about using this with reqwest and thus think of content_offset in terms of relative to header.

header_len indeed communicates the intent better than content_offset.

**Comment by Berrysoft** [comment]
New version 0.9.0 published with this new API.

**Comment by NobodyXu** [comment]
> New version 0.9.0 published with this new API.

Thank!

P.S. I don't think this is a breaking change, a patch release here should be ok.

**Pull request merged**
